//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/tests/CameraTestControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @CameraTestControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @CameraTestControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""CameraTestControls"",
    ""maps"": [
        {
            ""name"": ""CameraTest"",
            ""id"": ""f99e4214-a58a-41c5-a152-49ef57262257"",
            ""actions"": [
                {
                    ""name"": ""Look"",
                    ""type"": ""PassThrough"",
                    ""id"": ""2c1b8854-901b-445f-a5c4-f0890001cc38"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""cc0b066d-59ff-4c10-b782-dfd1c8038dc4"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // CameraTest
        m_CameraTest = asset.FindActionMap("CameraTest", throwIfNotFound: true);
        m_CameraTest_Look = m_CameraTest.FindAction("Look", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // CameraTest
    private readonly InputActionMap m_CameraTest;
    private List<ICameraTestActions> m_CameraTestActionsCallbackInterfaces = new List<ICameraTestActions>();
    private readonly InputAction m_CameraTest_Look;
    public struct CameraTestActions
    {
        private @CameraTestControls m_Wrapper;
        public CameraTestActions(@CameraTestControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Look => m_Wrapper.m_CameraTest_Look;
        public InputActionMap Get() { return m_Wrapper.m_CameraTest; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CameraTestActions set) { return set.Get(); }
        public void AddCallbacks(ICameraTestActions instance)
        {
            if (instance == null || m_Wrapper.m_CameraTestActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CameraTestActionsCallbackInterfaces.Add(instance);
            @Look.started += instance.OnLook;
            @Look.performed += instance.OnLook;
            @Look.canceled += instance.OnLook;
        }

        private void UnregisterCallbacks(ICameraTestActions instance)
        {
            @Look.started -= instance.OnLook;
            @Look.performed -= instance.OnLook;
            @Look.canceled -= instance.OnLook;
        }

        public void RemoveCallbacks(ICameraTestActions instance)
        {
            if (m_Wrapper.m_CameraTestActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ICameraTestActions instance)
        {
            foreach (var item in m_Wrapper.m_CameraTestActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CameraTestActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public CameraTestActions @CameraTest => new CameraTestActions(this);
    public interface ICameraTestActions
    {
        void OnLook(InputAction.CallbackContext context);
    }
}
